name: duckduckgo_search
description: DuckDuckGo Search API for Dart
version: 0.1.0
repository: https://github.com/kingwill101/duckduckgo_dart

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dio: 5.4.3+1
  html: 0.15.4
  html_unescape: ^2.0.0
  http: ^1.2.1
  xpath_selector: 3.0.2
  xpath_selector_html_parser: 3.0.1
  json_annotation: 4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
